# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_RESOURCE_GROUP: asurgent-cloudops-ui-rg-dev
  AZURE_LOCATION: westeurope

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
      - name: Deploy Azure resources
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "action_state=yellow" >> $GITHUB_ENV
            echo "{$action_state}"


