# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Get PR number

on:
  pull_request:
    types: [closed]

env:
  AZURE_RESOURCE_GROUP: asurgent-cloudops-ui-rg-dev
  AZURE_LOCATION: westeurope

jobs:
  
  prnumber:
    runs-on: ubuntu-latest

    steps:
      - name: Get pr number
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo GITHUB_REF=${GITHUB_REF}

            pr=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
            echo PR=$pr

            echo PR2=${{github.event.pull_request.number}}